# Generated by Django 5.2.6 on 2025-09-29 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_anuncios')),
                ('descripcion', models.TextField()),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('publicitario', 'publicitario'), ('alerta', 'alerta'), ('informativo', 'informativo')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_habitacion', models.IntegerField(unique=True)),
                ('cantidad_camas', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('Individual', 'Individual'), ('Doble', 'Doble'), ('Matrimonial', 'Matrimonial'), ('Triple', 'Triple'), ('Suite', 'Suite'), ('Familiar', 'Familiar')], max_length=30)),
                ('camas', models.CharField(choices=[('Individual', 'Individual'), ('Doble', 'Doble'), ('Queen', 'Queen'), ('King', 'King'), ('Extra Grande', 'Extra Grande')], max_length=30)),
                ('vistas', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Administrador', 'Administrador'), ('Recepcionista', 'Recepcionista'), ('Huesped', 'Huesped')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre_completo', models.CharField(max_length=200)),
                ('numero_telefonico', models.CharField(max_length=9, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre_completo', models.CharField(max_length=200)),
                ('numero_telefonico', models.CharField(max_length=9, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.trabajador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.trabajador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llegada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('huespedes_menores', models.BooleanField(blank=True, null=True)),
                ('preferencias', models.TextField(blank=True, null=True)),
                ('numero_reserva', models.CharField(blank=True, max_length=20, unique=True)),
                ('precio_total', models.IntegerField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.habitacion')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.trabajador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('habitacion', 'fecha_llegada', 'fecha_salida'), name='reserva general unica')],
            },
        ),
    ]
