# Generated by Django 5.2.6 on 2025-10-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='trabajador',
        ),
        migrations.RemoveField(
            model_name='reclamo',
            name='trabajador',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='trabajador',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
